// Generated by CoffeeScript 1.3.3
(function() {
  var $, adjIndex, adjs, genAdj, genBoth, genNoun, nounIndex, nouns;

  adjs = ['Serious', 'Alphabet', 'Absolute', 'Meditative', 'Fun', 'Edgy', 'Mathematical', 'Algebraic', 'Functional', 'Quasi', 'Erroneous', 'Special', 'Quirky', 'Miffed', 'Jumpy', 'Spastic', 'Creamy', 'Delicious', 'Singular', 'Fluid', 'Complete'];

  nouns = ['Design', 'Business', 'Programming', 'Studies', 'Creation', 'Observations', 'Associations', 'Commerce', 'Deductions', 'Soup', 'Dreams', 'Jargon', 'Context', 'Visions', 'Projects', 'Adventure', 'Conversations', 'Interactions'];

  $ = function(id) {
    return document.getElementById(id);
  };

  adjIndex = 0;

  nounIndex = 0;

  genAdj = function(index) {
    adjIndex = index != null ? index : index = Math.floor(Math.random() * adjs.length);
    $('adj').innerHTML = adjs[adjIndex];
    return window.location.hash = "" + adjIndex + "." + nounIndex;
  };

  genNoun = function(index) {
    nounIndex = index != null ? index : index = Math.floor(Math.random() * nouns.length);
    $('noun').innerHTML = nouns[nounIndex];
    return window.location.hash = "" + adjIndex + "." + nounIndex;
  };

  genBoth = function() {
    var indices;
    if (window.location.hash) {
      indices = window.location.hash.split('#').join('').split('.');
      genAdj(indices[0]);
      return genNoun(indices[1]);
    } else {
      genAdj();
      return genNoun();
    }
  };

  window.onload = function() {
    genBoth();
    $('adj').addEventListener('click', function() {
      return genAdj();
    });
    return $('noun').addEventListener('click', function() {
      return genNoun();
    });
  };

}).call(this);
