// Generated by CoffeeScript 1.3.3
(function() {
  var $, adjs, genAdj, genBoth, genNoun, nouns;

  adjs = ['Serious', 'Alphabet', 'Absolute', 'Meditative', 'Fun', 'Edgy', 'Mathematical', 'Algebraic', 'Functional', 'Quasi', 'Erroneous', 'Special', 'Quirky', 'Miffed', 'Jumpy', 'Spastic', 'Creamy', 'Delicious', 'Singular', 'Fluid', 'Complete'];

  nouns = ['Design', 'Business', 'Programming', 'Studies', 'Creation', 'Observations', 'Associations', 'Commerce', 'Deductions', 'Soup', 'Dreams', 'Jargon', 'Context', 'Visions', 'Projects', 'Adventure', 'Conversations', 'Interactions'];

  $ = function(id) {
    return document.getElementById(id);
  };

  genAdj = function() {
    var rnd;
    rnd = Math.floor(Math.random() * adjs.length);
    return $('adj').innerHTML = adjs[rnd];
  };

  genNoun = function() {
    var rnd;
    rnd = Math.floor(Math.random() * nouns.length);
    return $('noun').innerHTML = nouns[rnd];
  };

  genBoth = function() {
    genAdj();
    return genNoun();
  };

  window.onload = function() {
    genBoth();
    $('adj').addEventListener('click', function() {
      return genAdj();
    });
    return $('noun').addEventListener('click', function() {
      return genNoun();
    });
  };

}).call(this);
